### ISSUE TITLE
Bug in test

### ISSUE THREAD

**Issue by Dyer233** [zysszy/TreeGen-Pytorch#2]
There is a bug when running python3 run.py test

```
Traceback (most recent call last):
  File "run.py", line 466, in <module>
    test()
  File "run.py", line 450, in test
    ans = BeamSearch((x[0], x[1], x[5], x[2], x[3], x[4], x[6], x[7], x[8]), dev_set, model, 15, args.batch_size, index)
  File "run.py", line 358, in BeamSearch
    result = model(gVar(inputnl[0][validnum]), gVar(inputnl[1][validnum]), gVar(tmprule), gVar(tmpruleparent), gVar(tmprulechild), gVar(tmpAd), gVar(tmptreepath), gVar(tmpdepth), antimasks, None, "test")
  File "/home/zms-wzx/anaconda3/envs/TreeGen-app/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 2 required positional arguments: 'rulead' and 'antimask'
```

**Comment by zysszy** [comment]
This seems like a bug caused by using multi-GPUs. Maybe using a single GPU can be help.
